name: pet_ui
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  splashscreen: ^1.2.0
  url_launcher: ^5.4.2
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  audioplayers: ^0.20.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/alpha/
    - assets/farben/
    - assets/fragewoerterundrichtungsangaben/
    - assets/haeufigetwisaetze/
    - assets/konsonanten/
    - assets/selbstlaute/
    - assets/lebensmittel/
    - assets/wochentage/
    - assets/zahlen/
    - assets/zeitangaben/
    - assets/tiere/
    - assets/images/thesac-sanky.jpg
    - assets/images/Sankofa_Sprachkurs.png
    - assets/images/Lingala.jpeg
    - assets/images/Swahili.jpeg
    - assets/images/unnamed.png
    - assets/images/KomplettesQuizBild.jpeg
    - assets/images/FarbenBild.jpeg
    - assets/images/ZahlenBild.jpeg
    - assets/images/LebensmittelBild.jpeg
    - assets/images/WochenTageBild.jpeg
    - assets/images/KonsonantenBild.jpeg
    - assets/images/SelbstlauteBild.jpeg
    - assets/images/HaeufigeTwiSaetzeBild.jpeg
    - assets/images/FragewoerterBild.jpeg
    - assets/images/ZeitangabenBild.jpeg
    - assets/images/TiereBild.jpeg
    - assets/images/okay.jpeg
    - assets/images/good.jpeg
    - assets/images/success.jpeg
    - assets/images/SankofaNeuesBild1.jfif
    - assets/images/SankofaNeuesBild2.jfif
    - assets/images/SankofaNeuesBild3.jfif
    - assets/images/SankofaNeuesBild4.jfif
    - assets/images/SankofaNeuesBild5.jfif
    - assets/images/SankofaNeuesBild6.jfif
    - assets/images/SankofaNeuesBild7.jfif
    - assets/quize/farbenquiz.json
    - assets/quize/fragewoerterundrichtungsangabenquiz.json
    - assets/quize/haeufigetwisaetzequiz.json
    - assets/quize/komplettesquiz.json
    - assets/quize/konsonantenquiz.json
    - assets/quize/lebensmittelquiz.json
    - assets/quize/numberquiz.json
    - assets/quize/selbstlautequiz.json
    - assets/quize/tierequiz.json
    - assets/quize/wochentagequiz.json
    - assets/quize/zeitangabenquiz.json


  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
